#!/usr/bin/env python
from docopt import docopt
import sys

from superk_control.superk import SuperK

__doc__ = """
Usage:
    superk -h | --help
    superk power (on | off)
    superk flux [<value>]
    superk filter <pos>

Options:
    -h --help           Print this message

Commands:
    power (on | off)    Turn source on or off (case insensitive)
    flux [<value>]      Change the intensity value of the source (0 to 100). If no value provided, return current flux
    filter <pos>        (INACTIVE) Change the ND filter in the source
"""


if __name__ == "__main__":
    args = docopt(__doc__)

    superk = SuperK()

    if args["power"]:
        option = args["power"]
        if args["on"]:
            superk.power_on()
        elif args["off"]:
            superk.power_off()
    elif args["flux"]:
        if args["<value>"]:
            value = float(args["<value>"])
            superk.set_flux(value)
        else:
            value = superk.get_flux()
            print(f"{value}")
    elif args["filter"]:
        print(f"No filter options yet")
        sys.exit(1)

    sys.exit(0)
