#!/usr/bin/env python
from docopt import docopt
import sys

__doc__ = """
Usage:
    superk -h | --help
    superk power (on | off)
    superk flux <value>
    superk filter <pos>

Options:
    -h --help           Print this message

Commands:
    power (on | off)    Turn source on or off (case insensitive)
    flux <value>        Change the intensity value of the source (0 to 100)
    filter <pos>        (INACTIVE) Change the ND filter in the source
"""

def flux_bar(flux_value, width=40):
    frac = flux_value / 100
    num_fill = int(frac * width)
    rest = width - num_fill
    return f"{0} {'█' * num_fill}{'-' * rest} {100}"


if __name__ == "__main__":
    args = docopt(__doc__)
    if args["power"]:
        option = args["power"]
        if args["on"]:
            print("\x1b[42mSOURCE TURNED ON")
            # todo
        elif args["off"]:
            print("\x1b[41mSOURCE TURNED OFF")
            # todo
    elif args["flux"]:
        value = float(args["<value>"])
        if value < 0 or value > 100:
            print(f"could not parse flux value {value}, should be between 0 and 100")
            sys.exit(1)
        else:
            print(f"Flux set to: {value}")
            print(flux_bar(value))
            # todo
    elif args["filter"]:
        print(f"No filter options yet")
        sys.exit(1)

    sys.exit(0)


